/**
 * Arthur D. Little - Global Health Platform
 * Country Data Registry - 3-Step Wizard Interface
 * 
 * Features:
 * - Step 1: Select countries with visual grid
 * - Step 2: Choose data layers/categories
 * - Step 3: Interactive pivot table with drag-and-drop
 * - Excel export with descriptive filename
 */

import { useState, useCallback, useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { motion, AnimatePresence } from "framer-motion";
import { Loader2, AlertTriangle, Table2 } from "lucide-react";
import {
  fetchCountryDataCountries,
  fetchCountryDataCategories,
  fetchPivotTable,
} from "../services/api";
import type { PivotTableResponse } from "../services/api";
import {
  StepIndicator,
  CountrySelectionStep,
  DataLayerStep,
  InteractivePivotTable,
} from "../components/country-data";

// ============================================================================
// EXCEL EXPORT FUNCTION
// ============================================================================

async function exportToExcel(
  data: PivotTableResponse,
  selectedCategories: string[]
) {
  const XLSX = await import("xlsx");

  const wb = XLSX.utils.book_new();

  // Main data sheet
  const headers = [
    "Metric",
    "Unit",
    ...data.countries.map((c) => `${c.name} (${c.iso_code})`),
  ];

  const rows = data.rows.map((row) => [
    row.metric.name,
    row.metric.unit || "-",
    ...row.values.map((v) => v.formatted_value),
  ]);

  const wsData = [headers, ...rows];
  const ws = XLSX.utils.aoa_to_sheet(wsData);

  const colWidths = [
    { wch: 30 },
    { wch: 12 },
    ...data.countries.map(() => ({ wch: 15 })),
  ];
  ws["!cols"] = colWidths;

  XLSX.utils.book_append_sheet(wb, ws, "Country Data");

  // Metadata sheet
  const metaData = [
    ["Country Data Export"],
    [""],
    ["Export Date", new Date().toISOString().split("T")[0]],
    ["Export Time", new Date().toISOString().split("T")[1].split(".")[0]],
    [""],
    ["Countries Included"],
    ...data.countries.map((c) => [c.name, c.iso_code]),
    [""],
    ["Categories Included"],
    ...selectedCategories.map((c) => [c]),
    [""],
    ["Total Metrics", data.total_metrics.toString()],
    [""],
    ["Source", "Global Occupational Health Platform (GOHIP)"],
    ["Generated By", "Arthur D. Little"],
  ];

  const metaWs = XLSX.utils.aoa_to_sheet(metaData);
  metaWs["!cols"] = [{ wch: 25 }, { wch: 40 }];
  XLSX.utils.book_append_sheet(wb, metaWs, "Export Info");

  const dateStr = new Date().toISOString().split("T")[0].replace(/-/g, "");
  const countryCount = data.countries.length;
  const filename = `GOHIP_CountryData_${countryCount}countries_${dateStr}.xlsx`;

  XLSX.writeFile(wb, filename);
}

// ============================================================================
// MAIN COMPONENT
// ============================================================================

export function CountryData() {
  // Wizard state
  const [currentStep, setCurrentStep] = useState(1);
  const [selectedCountries, setSelectedCountries] = useState<string[]>([]);
  const [selectedCategories, setSelectedCategories] = useState<string[]>([]);

  // Fetch available countries
  const {
    data: countriesData,
    isLoading: countriesLoading,
    error: countriesError,
  } = useQuery({
    queryKey: ["country-data-countries"],
    queryFn: fetchCountryDataCountries,
    staleTime: 5 * 60 * 1000,
  });

  // Fetch available categories
  const {
    data: categoriesData,
    isLoading: categoriesLoading,
    error: categoriesError,
  } = useQuery({
    queryKey: ["country-data-categories"],
    queryFn: fetchCountryDataCategories,
    staleTime: 10 * 60 * 1000,
  });

  // Fetch pivot table data (only when on step 3)
  const {
    data: pivotData,
    isLoading: pivotLoading,
    error: pivotError,
    refetch: refetchPivot,
  } = useQuery({
    queryKey: ["pivot-table", selectedCountries, selectedCategories],
    queryFn: () => fetchPivotTable(selectedCountries, selectedCategories),
    enabled:
      currentStep === 3 &&
      selectedCountries.length > 0 &&
      selectedCategories.length > 0,
    staleTime: 60 * 1000,
  });

  // Computed completed steps
  const completedSteps = useMemo(() => {
    const completed: number[] = [];
    if (selectedCountries.length > 0) completed.push(1);
    if (selectedCategories.length > 0) completed.push(2);
    if (pivotData) completed.push(3);
    return completed;
  }, [selectedCountries, selectedCategories, pivotData]);

  // Navigation handlers
  const handleStepClick = (step: number) => {
    // Allow going back to previous steps
    if (step <= currentStep || completedSteps.includes(step - 1)) {
      setCurrentStep(step);
    }
  };

  const handleContinueToStep2 = useCallback(() => {
    if (selectedCountries.length > 0) {
      setCurrentStep(2);
    }
  }, [selectedCountries]);

  const handleContinueToStep3 = useCallback(() => {
    if (selectedCategories.length > 0) {
      setCurrentStep(3);
    }
  }, [selectedCategories]);

  const handleBackToStep1 = useCallback(() => {
    setCurrentStep(1);
  }, []);

  const handleBackToStep2 = useCallback(() => {
    setCurrentStep(2);
  }, []);

  const handleExport = useCallback(async () => {
    if (!pivotData) return;
    await exportToExcel(pivotData, selectedCategories);
  }, [pivotData, selectedCategories]);

  // Loading state
  const isInitialLoading = countriesLoading || categoriesLoading;
  const hasError = countriesError || categoriesError;

  if (isInitialLoading) {
    return (
      <div className="flex items-center justify-center min-h-[500px]">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          className="flex flex-col items-center gap-4"
        >
          <div className="relative">
            <div className="w-16 h-16 bg-gradient-to-br from-cyan-500/20 to-indigo-500/20 rounded-2xl flex items-center justify-center border border-cyan-500/30">
              <Loader2 className="w-8 h-8 text-cyan-400 animate-spin" />
            </div>
          </div>
          <div className="text-center">
            <p className="text-white font-medium">Loading Data Registry</p>
            <p className="text-sm text-slate-400 mt-1">
              Preparing countries and data layers...
            </p>
          </div>
        </motion.div>
      </div>
    );
  }

  if (hasError) {
    return (
      <div className="flex items-center justify-center min-h-[500px]">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          className="text-center"
        >
          <div className="w-16 h-16 bg-red-500/20 rounded-2xl flex items-center justify-center border border-red-500/30 mx-auto mb-4">
            <AlertTriangle className="w-8 h-8 text-red-400" />
          </div>
          <p className="text-white font-medium">Failed to load data registry</p>
          <p className="text-sm text-slate-400 mt-1">
            Please ensure the backend is running and try again.
          </p>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col overflow-hidden">
      {/* Page Header */}
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex-shrink-0 mb-6"
      >
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 bg-gradient-to-br from-indigo-500/20 to-purple-500/20 rounded-xl flex items-center justify-center border border-indigo-500/30">
            <Table2 className="w-6 h-6 text-indigo-400" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-white tracking-tight">
              Country Data Registry
            </h1>
            <p className="text-slate-400">
              Build custom data tables with drag-and-drop pivot functionality
            </p>
          </div>
        </div>
      </motion.div>

      {/* Step Indicator */}
      <div className="flex-shrink-0">
        <StepIndicator
          currentStep={currentStep}
          completedSteps={completedSteps}
          onStepClick={handleStepClick}
        />
      </div>

      {/* Step Content */}
      <div className="flex-1 overflow-auto">
        <AnimatePresence mode="wait">
          {currentStep === 1 && (
            <CountrySelectionStep
              key="step-1"
              countries={countriesData?.countries || []}
              selectedCountries={selectedCountries}
              onSelectionChange={setSelectedCountries}
              onContinue={handleContinueToStep2}
              maxSelections={10}
            />
          )}

          {currentStep === 2 && (
            <DataLayerStep
              key="step-2"
              categories={categoriesData?.categories || []}
              selectedCategories={selectedCategories}
              onSelectionChange={setSelectedCategories}
              onBack={handleBackToStep1}
              onContinue={handleContinueToStep3}
            />
          )}

          {currentStep === 3 && (
            <motion.div
              key="step-3"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
            >
              {pivotLoading ? (
                <div className="flex items-center justify-center min-h-[400px]">
                  <div className="flex flex-col items-center gap-4">
                    <Loader2 className="w-8 h-8 text-cyan-400 animate-spin" />
                    <div className="text-center">
                      <p className="text-white font-medium">
                        Generating Pivot Table
                      </p>
                      <p className="text-sm text-slate-400 mt-1">
                        Processing {selectedCountries.length} countries across{" "}
                        {selectedCategories.length} categories...
                      </p>
                    </div>
                  </div>
                </div>
              ) : pivotError ? (
                <div className="flex items-center justify-center min-h-[400px]">
                  <div className="text-center">
                    <AlertTriangle className="w-12 h-12 text-red-400 mx-auto mb-4" />
                    <p className="text-white font-medium">
                      Failed to generate pivot table
                    </p>
                    <button
                      onClick={() => refetchPivot()}
                      className="mt-4 px-4 py-2 bg-slate-700 rounded-lg text-white hover:bg-slate-600 transition-colors"
                    >
                      Retry
                    </button>
                  </div>
                </div>
              ) : pivotData ? (
                <InteractivePivotTable
                  data={pivotData}
                  onBack={handleBackToStep2}
                  onExport={handleExport}
                />
              ) : null}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}

export default CountryData;
