"""add_flag_url_to_countries

Revision ID: 22b15c2dba08
Revises: b1c2d3e4f5g6
Create Date: 2026-01-28 22:10:29.721610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22b15c2dba08'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5g6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if columns exist before adding (idempotent migration)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    # ### commands auto generated by Alembic - please adjust! ###
    # These alter_column calls add comments - only run if table exists
    if 'ai_config' in tables:
        op.alter_column('ai_config', 'provider',
                   existing_type=postgresql.ENUM('openai', 'anthropic', 'google', 'local', 'azure_openai', 'mistral', 'cohere', 'ollama', name='aiprovider'),
                   comment='Selected AI provider',
                   existing_nullable=False)
        op.alter_column('ai_config', 'model_name',
                   existing_type=sa.VARCHAR(length=100),
                   comment='Model identifier (e.g., gpt-4o, claude-3-opus, gemini-pro)',
                   existing_nullable=False)
        op.alter_column('ai_config', 'api_key_encrypted',
                   existing_type=sa.TEXT(),
                   comment='Encrypted API key for the provider',
                   existing_nullable=True)
        op.alter_column('ai_config', 'api_endpoint',
                   existing_type=sa.VARCHAR(length=500),
                   comment='Custom API endpoint URL (for Azure, local models, etc.)',
                   existing_nullable=True)
        op.alter_column('ai_config', 'extra_settings',
                   existing_type=postgresql.JSONB(astext_type=sa.Text()),
                   comment='Additional provider-specific configuration',
                   existing_nullable=True)
    
    # Check if flag_url column exists before adding
    if 'countries' in tables:
        columns = [col['name'] for col in inspector.get_columns('countries')]
        if 'flag_url' not in columns:
            op.add_column('countries', sa.Column('flag_url', sa.String(length=255), nullable=True, comment='URL path to country flag image'))
    
    if 'users' in tables:
        op.alter_column('users', 'role',
                   existing_type=postgresql.ENUM('admin', 'user', 'viewer', name='userrole'),
                   comment='User role for access control',
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'user', 'viewer', name='userrole'),
               comment=None,
               existing_comment='User role for access control',
               existing_nullable=False)
    op.drop_column('countries', 'flag_url')
    op.alter_column('ai_config', 'extra_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional provider-specific configuration',
               existing_nullable=True)
    op.alter_column('ai_config', 'api_endpoint',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Custom API endpoint URL (for Azure, local models, etc.)',
               existing_nullable=True)
    op.alter_column('ai_config', 'api_key_encrypted',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Encrypted API key for the provider',
               existing_nullable=True)
    op.alter_column('ai_config', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Model identifier (e.g., gpt-4o, claude-3-opus, gemini-pro)',
               existing_nullable=False)
    op.alter_column('ai_config', 'provider',
               existing_type=postgresql.ENUM('openai', 'anthropic', 'google', 'local', 'azure_openai', 'mistral', 'cohere', 'ollama', name='aiprovider'),
               comment=None,
               existing_comment='Selected AI provider',
               existing_nullable=False)
    # ### end Alembic commands ###
