"""densify_schema_phase_11

Revision ID: 30a72d216fde
Revises: a1b2c3d4e5f6
Create Date: 2026-01-28 17:37:59.007320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a72d216fde'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name: str, column_name: str) -> bool:
    """Check if a column exists in a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Idempotent: check if columns exist before adding
    
    # pillar_1_hazard columns
    if not column_exists('pillar_1_hazard', 'oel_compliance_pct'):
        op.add_column('pillar_1_hazard', sa.Column('oel_compliance_pct', sa.Float(), nullable=True, comment='Occupational Exposure Limit compliance percentage'))
    if not column_exists('pillar_1_hazard', 'noise_induced_hearing_loss_rate'):
        op.add_column('pillar_1_hazard', sa.Column('noise_induced_hearing_loss_rate', sa.Float(), nullable=True, comment='NIHL rate per 100,000 workers'))
    if not column_exists('pillar_1_hazard', 'safety_training_hours_avg'):
        op.add_column('pillar_1_hazard', sa.Column('safety_training_hours_avg', sa.Float(), nullable=True, comment='Average annual safety training hours per worker'))
    
    # pillar_2_vigilance columns
    if not column_exists('pillar_2_vigilance', 'migrant_worker_pct'):
        op.add_column('pillar_2_vigilance', sa.Column('migrant_worker_pct', sa.Float(), nullable=True, comment='Migrant workforce percentage'))
    if not column_exists('pillar_2_vigilance', 'lead_exposure_screening_rate'):
        op.add_column('pillar_2_vigilance', sa.Column('lead_exposure_screening_rate', sa.Float(), nullable=True, comment='Lead exposure screening rate per 100,000'))
    if not column_exists('pillar_2_vigilance', 'occupational_disease_reporting_rate'):
        op.add_column('pillar_2_vigilance', sa.Column('occupational_disease_reporting_rate', sa.Float(), nullable=True, comment='Disease reporting compliance rate (%)'))
    
    # pillar_3_restoration columns
    if not column_exists('pillar_3_restoration', 'return_to_work_success_pct'):
        op.add_column('pillar_3_restoration', sa.Column('return_to_work_success_pct', sa.Float(), nullable=True, comment='Return-to-work program success rate (%)'))
    if not column_exists('pillar_3_restoration', 'avg_claim_settlement_days'):
        op.add_column('pillar_3_restoration', sa.Column('avg_claim_settlement_days', sa.Float(), nullable=True, comment="Average days to settle workers' comp claim"))
    if not column_exists('pillar_3_restoration', 'rehab_participation_rate'):
        op.add_column('pillar_3_restoration', sa.Column('rehab_participation_rate', sa.Float(), nullable=True, comment='Rehabilitation program participation rate (%)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pillar_3_restoration', 'rehab_participation_rate')
    op.drop_column('pillar_3_restoration', 'avg_claim_settlement_days')
    op.drop_column('pillar_3_restoration', 'return_to_work_success_pct')
    op.drop_column('pillar_2_vigilance', 'occupational_disease_reporting_rate')
    op.drop_column('pillar_2_vigilance', 'lead_exposure_screening_rate')
    op.drop_column('pillar_2_vigilance', 'migrant_worker_pct')
    op.drop_column('pillar_1_hazard', 'safety_training_hours_avg')
    op.drop_column('pillar_1_hazard', 'noise_induced_hearing_loss_rate')
    op.drop_column('pillar_1_hazard', 'oel_compliance_pct')
    # ### end Alembic commands ###
