"""
GOHIP Platform - Comparison Report Model
Stores cached AI-generated comparison reports for country benchmarking.

Reports are cached to avoid regenerating expensive AI analysis.
Only admins can force regeneration.
"""

from datetime import datetime
from typing import Optional

from sqlalchemy import (
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.core.database import Base


class ComparisonReport(Base):
    """
    Cached comparison report between Saudi Arabia and another country.
    
    The primary country is always Saudi Arabia (SAU).
    Reports are generated by the McKinsey Research Analyst AI agent.
    """
    __tablename__ = "comparison_reports"

    # Primary key: "SAU_DEU", "SAU_FRA", etc.
    id = Column(String(10), primary_key=True)
    
    # Country references
    primary_iso = Column(
        String(3), 
        ForeignKey("countries.iso_code", ondelete="CASCADE"),
        nullable=False,
        default="SAU"
    )
    comparison_iso = Column(
        String(3), 
        ForeignKey("countries.iso_code", ondelete="CASCADE"),
        nullable=False
    )
    
    # AI-generated content
    executive_summary = Column(Text, nullable=True)
    
    # Per-pillar analysis (JSON array)
    # Structure: [{pillar, saudi_score, comparison_score, gap, analysis, key_metrics}]
    framework_analysis = Column(JSONB, nullable=True)
    
    # Socioeconomic comparison (JSON object)
    # Structure: {gdp, population, health_expenditure, life_expectancy, hdi, etc.}
    socioeconomic_comparison = Column(JSONB, nullable=True)
    
    # Detailed metric comparisons (JSON array)
    # Structure: [{metric_id, metric_name, saudi_value, comparison_value, gap_pct, interpretation}]
    metric_comparisons = Column(JSONB, nullable=True)
    
    # Strategic recommendations (JSON array)
    # Structure: [{priority, title, description, impact, complexity, timeline}]
    strategic_recommendations = Column(JSONB, nullable=True)
    
    # Data sources cited (JSON array)
    # Structure: ["World Bank", "ILO", "WHO", ...]
    sources_cited = Column(JSONB, nullable=True)
    
    # Metadata
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, onupdate=func.now(), nullable=True)
    created_by = Column(String(100), nullable=True)  # User email or ID
    version = Column(Integer, default=1, nullable=False)
    generation_time_seconds = Column(Float, nullable=True)
    
    # Relationships
    primary_country = relationship(
        "Country",
        foreign_keys=[primary_iso],
        backref="comparison_reports_as_primary"
    )
    comparison_country = relationship(
        "Country",
        foreign_keys=[comparison_iso],
        backref="comparison_reports_as_comparison"
    )
    
    def __repr__(self) -> str:
        return f"<ComparisonReport {self.id}: {self.primary_iso} vs {self.comparison_iso}>"
    
    @classmethod
    def generate_id(cls, primary_iso: str, comparison_iso: str) -> str:
        """Generate report ID from country ISO codes."""
        return f"{primary_iso}_{comparison_iso}"
    
    def to_dict(self) -> dict:
        """Convert to dictionary for API response."""
        return {
            "id": self.id,
            "primary_iso": self.primary_iso,
            "comparison_iso": self.comparison_iso,
            "executive_summary": self.executive_summary,
            "framework_analysis": self.framework_analysis,
            "socioeconomic_comparison": self.socioeconomic_comparison,
            "metric_comparisons": self.metric_comparisons,
            "strategic_recommendations": self.strategic_recommendations,
            "sources_cited": self.sources_cited,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
            "created_by": self.created_by,
            "version": self.version,
            "generation_time_seconds": self.generation_time_seconds,
        }
